# Users and groups: these should not be changed
postgres_uid:  "70"
postgres_gid:  "70"
mailman_uid:  "100"
mailman_gid:  "101"
postfix_uid:  "100"
postfix_gid:    "0"
opendkim_uid: "102"
opendkim_gid: "103"
nginx_uid:      "0"
nginx_gid:      "0"
