#
# Simple playbook for Amazon Web Services EC2 hosts. It detects the current
# Terraform environment by reading .terraform/environment. Then, it loads
# default and environment-specific vars from env_vars.
#
# When run inside Terraform:
#
#         ansible-playbook -i hosts_aws_ec2.yml \
#             --ssh-extra-args='-o StrictHostKeyChecking=no' \
#             playbook_ec2.yml
#
# When run from the command line:
# 
#         ansible-playbook playbook_ec2.yml
#
- hosts:  "{{ lookup('file', '{{ playbook_dir }}/.terraform/environment') }}"
  become: yes
  gather_facts: yes
  no_log: no
  
  tasks:
    - import_role:
        name: base
    - import_role:
        name: amazon
      when: is_ec2_environment == true
    - import_role:
        name: keys
      run_once: yes
