#
# Simple playbook for Amazon Web Services EC2 hosts. It detects the current
# Terraform environment by reading .terraform/environment. Then, it loads
# default and environment-specific vars from env_vars.
#
# When run inside Terraform:
#
#         ansible-playbook \
#             --ssh-extra-args='-o StrictHostKeyChecking=no' \
#             playbook.yml
#
# When run from the command line:
# 
#         ansible-playbook playbook.yml
#
- hosts:  "{{ lookup('file', '{{ playbook_dir }}/.terraform/environment') }}"
  become: yes
  gather_facts: yes
  no_log: no

  pre_tasks:
    - name: Set private zone
      set_fact:
        private_zone: "{{ ec2_env }}.local"
  
  tasks:
    - import_role:
        name: base
    - import_role:
        name: amazon
      when: is_ec2_env == true
    - import_role:
        name: keys
      run_once: yes
    - import_role:
        name: mailman
      run_once: yes
    - import_role:
        name: import_archive
      when: import_archive == true
