#
# Simple playbook for Amazon Web Services EC2 hosts. It detects the current
# Terraform environment by reading .terraform/environment. Then, it loads
# default and environment-specific vars from env_vars.
#
# When run inside Terraform:
#
#         ansible-playbook -i hosts_aws_ec2.yml \
#             --user alpine \
#             --private-key ~/.ssh/id_rsa \
#             --ssh-extra-args='-o StrictHostKeyChecking=no' \
#             playbook_ec2.yml
#
# When run from the command line:
# 
#         ansible-playbook playbook_ec2.yml
#
- hosts:  "{{ lookup('file', '{{ playbook_dir }}/.terraform/environment') }}"
  become: yes
  gather_facts: yes
  no_log: no

  pre_tasks:
    - set_fact:
        is_ec2_environment: "{{ 'amazon' in ansible_bios_version }}"
    - include_vars:
        file: "env_vars/default/main.yml"
    - block:
        - ec2_metadata_facts:
        - set_fact:
            ec2_region: "{{ ansible_facts.ec2_placement_region }}"
            ec2_environment: "{{ lookup('file', '{{ playbook_dir }}/.terraform/environment') }}"
        - include_vars:
            file: "env_vars/{{ ec2_environment }}/main.yml"
      when: is_ec2_environment == true
  
  tasks:
    - import_role:
        name: base
    - import_role:
        name: amazon
      when: is_ec2_environment == true
