- name: Install AWS EFS required packages
  apk:
    name: ['nfs-utils', 'openssl', 'stunnel']
    state: present

- name: Clone the lastest AWS EFS git repo
  local_action:
    module: git
    repo: https://github.com/aws/efs-utils.git
    dest: etc/local/efs-utils
    force: yes
  run_once: yes
  become: no

- name: Get AWS EFS version
  local_action: command awk -F "=" '/^VERSION/{print $NF}' etc/local/efs-utils/build-deb.sh
  become: no
  register: aws_efs_version
  
- name: Save AWS EFS version
  set_fact:
    aws_efs_version: "{{ aws_efs_version.stdout }}"

- name: Create AWS EFS directories
  file:
    path: "{{ item }}/"
    state: directory
  with_items:
    - /etc/amazon/efs
    - /var/log/amazon/efs
    - /var/run/efs

- name: Copy AWS EFS config
  template:
    src: efs/efs-utils.conf
    dest: /etc/amazon/efs/
    mode: "u=w,g=w,o=w"
  notify: Restart AWS EFS watchdog

- name: Copy AWS EFS certificates
  copy:
    src: etc/local/efs-utils/dist/efs-utils.crt
    dest: /etc/amazon/efs/
    mode: "u=w,g=w,o=w"
  notify: Restart AWS EFS watchdog
    
- name: Patch AWS EFS watchdog
  local_action:
    module: patch
    src: amazon-efs-mount-watchdog.patch
    dest: "{{ playbook_dir }}/etc/local/efs-utils/src/watchdog/__init__.py"
    strip: 1
  run_once: yes
  become: no

- name: Copy AWS EFS watchdog
  copy:
    src: etc/local/efs-utils/src/watchdog/__init__.py
    dest: /usr/bin/amazon-efs-mount-watchdog
    mode: "u=rwx,g=rx,o=rx"
  notify: Restart AWS EFS watchdog

- name: Patch AWS EFS mount.efs
  local_action:
    module: patch
    src: mount.efs.patch
    dest: "{{ playbook_dir }}/etc/local/efs-utils/src/mount_efs/__init__.py"
    strip: 1
  run_once: yes
  become: no

- name: Copy AWS EFS mount.efs
  copy:
    src: etc/local/efs-utils/src/mount_efs/__init__.py
    dest: /sbin/mount.efs
    mode: "u=rwx,g=rx,o=rx"
  notify: Restart AWS EFS watchdog

- name: Create AWS EFS watchdog daemon
  template:
    src: efs/amazon-efs-mount-watchdog.initd
    dest: /etc/init.d/amazon-efs-mount-watchdog
    mode: "u=rwx,g=rx,o=rx"
  notify: Restart AWS EFS watchdog
