- name: Install AWS Docker services
  apk:
    name: ['aws-docker@arj']
    state: present

- name: Enable AWS Log Agent service
  service:
    name: awslogs
    state: started
    enabled: yes

- name: Run ECS Agent
  docker_container:
    name: ecs-agent
    image: amazon/amazon-ecs-agent:latest
    state: started
    detach: yes
    restart_policy: on-failure
    restart_retries: 10
    network_mode: host
    env_file: /etc/ecs/ecs.config
    env:
      ECS_LOGFILE=/log/ecs-agent.log
      ECS_DATADIR=/data/
      ECS_ENABLE_TASK_IAM_ROLE=true
      ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/ecs:/log
      - /var/lib/ecs/data:/data
