- name: Get AWS credentials
  set_fact:
    aws_access_key: "{{ lookup('ini', 'aws_access_key_id section=default file=~/.aws/credentials') }}"
    aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section=default file=~/.aws/credentials') }}"

- name: Register DNS MX record for EC2 host
  local_action:
    module: route53
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    zone: "{{ public_domain }}"
    record: "{{ public_domain }}"
    type: MX
    ttl: 300
    value: "10 mail.{{ public_domain }}."
    overwrite: yes
    wait: yes
  become: no

- name: "Register SPF record for {{ public_domain }}"
  local_action:
    module: route53
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    zone: "{{ public_domain }}"
    record: "{{ public_domain }}"
    type: TXT
    ttl: 3600
    value: '"v=spf1 mx -all"'
    overwrite: yes
    wait: yes
  become: no

- name: "Register DKIM record"
  local_action:
    module: route53
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    zone: "{{ public_domain }}"
    record: "mail._domainkey.{{ public_domain }}"
    type: TXT
    ttl: 3600
    value: "{{ dkim_public_key.stdout | dkim_record }}"
    overwrite: yes
    wait: yes
  become: no
