ec2_ssh_key_name:  Andy SSH                      # Name for uploaded SSH key
ec2_ssh_key:       ~/.ssh/id_rsa.pub             # Local path to SSH key
ec2_iam_role:      AlpineContainer               # Role to attach to EC2 instances
ec2_instance_type: t2.nano                       # Size of EC2 instance to provision
ec2_region:        us-east-1                     # Region to deploy AWS environment
ec2_subnet_1_az:   us-east-1a
ec2_subnet_2_az:   us-east-1b
ec2_instance_ami:  ami-039eb499c36219cad         # ID of the AMI used for EC2 instances
ansible_playbook:  playbook_ec2.yml              # Ansible playbook for provisioning EC2 instances
import_archive:    no
